# Generated by Django 3.0.8 on 2020-07-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_command_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='command',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
